### ISSUE TITLE
cannot merge

### ISSUE THREAD

**Issue by ABCorpuz** [BarlaanArynne/BSIT-TSM-3A-IPT2CS-G4#9]
![image](https://github.com/BarlaanArynne/BSIT-TSM-3A-IPT2CS-G4/assets/159202236/6fb0122c-4bd5-49fd-bcfc-2313f2c8581c)

does anyone know how to do this?? it seems like it wants some message

**Comment by BarlaanArynne** [comment]
time stamp 0:25 in the video typing ":qa!" will abort commit so I suggest this instead
For closing the “vi” Git commit editor, type the “:wq” command, where “:” helps to enter in the command mode because “vi” is a mode-based editor, “w” is for writing and saving the added commit, and “q” is to exit. Press the “Enter” key after specifying the mentioned command. This operation will save the added commit message and closet the Git editor. source: https://linuxhint.com/close-git-commit-editor-windows/

**Comment by ABCorpuz** [comment]
i've tried that and it worked. thank you : ))
